components:
  noclientmods:
    enabled: true
  password:
    FromGroup: guest
    ToGroup: member
    PasswordLength: 5
    messages:
      Congratulations:
      - '&3You have been promoted to &b{togroup}&3!'
      Announcement: '&b{player}&3 has become a &b{togroup}&3!'
  rules:
    Rules:
    - '&7* &cRULES&7 *'
    - '&c* &7No &cgriefing&7, &cstealing&7 or &cspamming&7.'
    - '&c* &7Do not &cexploit glitches&7 or use &cunfair client mods&7.'
    - '&c* &7No &cwhining&7 or &coffensive language&7. Be respectful.'
    - '&c* &7No &cugly&7 or &coffensive&7 builds or &c1x1&7 towers.'
    - '&c* &7Use &ccommon sense&7 and do not create unreasonable &clag&7.'
    PasswordLine: '&c* &7Become member via &c/pw {password}&7.'
  motd:
    Message:
    - '&3Welcome to &bWinnilla&3 - Winthier semi vanilla MC server'
  message:
    help:
      ErrorMessage: '&4Unknown help section'
      Message:
      - '&3Help Screen'
      - '&7This is the default &bHelp&7 screen provided by the Winthier plugin.'
  playermessages:
    DeathMessageColor: '8'
    JoinMessage: '&8{player} joined'
    LeaveMessage: '&8{player} left'
  chat:
    ConsoleName: 'Console'
    me:
      Format: '&f* &6{player} &f{message}'
    msg:
      SenderFormat: '&7to &f{to}&7: {message}'
      RecipientFormat: '&7from &f{from}&7: {message}'
  newbiewatch:
    MaxBlockBreaks: 100
    BlockBreaks: [ glass, glowstone, thin-glass, redstone-lamp-off, redstone-lamp-on, bed_block, diamond-block, diamond-ore, gold-block, cauldron, bookshelf, brewing-stand, enchantment_table, ender-chest, iron_block, jukebox, lapis-block, redstone-wire, diode-block-off, diode-block-on, redstone-torch-off, redstone-torch-on, iron-fence, rails, powered-rail, detector-rail, emerald-block, dragon-egg ]
    BlockBreakMessage: '&4New player &c{player}&4 broke &c{block}'
  wither:
    regions: []