name: Winthier
main: com.winthier.WinthierPlugin
version: 0.1
author: StarTux
description: The Winthier Plugin
depends: [ Vault ]
commands:
  pw:
    description: Become a member
    usage: /<command> <password>
    permission: winthier.cmd.pw
  winthier:
    description: General purpose command
    usage: /<command> help
    permission: winthier.cmd.winthier
  rules:
    description: Display server rules
    usage: /<command>
    permission: winthier.cmd.rules
  ignore:
    description: Ignore another player in chat
    usage: /<command> <player>
    permission: winthier.cmd.ignore
permissions:
  winthier.cmd.pw:
    description: Use the /pw command to become a member
    default: false
  winthier.cmd.wintier:
    description: Use the /winthier command
    default: op
  winthier.cmd.rules:
    description: Use the /rules command
    default: op
  winthier.password.notify:
    description: Get notified when a user gets promoted after entering the correct password.
  winthier.joinleavemsg:
    description: Display a message when the player joins or leaves.
    default: op
  winthier.deathmessage.visible:
    description: Send a message upon player death
    default: false
  winthier.cheatmods:
    description: Permit the use of cheaty clientmods.
    default: op
  winthier.signcolor.allcolors:
    description: Permit the use of all color codes on signs.
    default: op
    children:
    - winthier.signcolor.0
    - winthier.signcolor.1
    - winthier.signcolor.2
    - winthier.signcolor.3
    - winthier.signcolor.4
    - winthier.signcolor.5
    - winthier.signcolor.6
    - winthier.signcolor.7
    - winthier.signcolor.8
    - winthier.signcolor.9
    - winthier.signcolor.a
    - winthier.signcolor.b
    - winthier.signcolor.c
    - winthier.signcolor.d
    - winthier.signcolor.e
    - winthier.signcolor.f
  winthier.signcolor.allformats:
    description: Permit the use of all formatting codes on signs.
    default: op
    children:
    - winthier.signcolor.k
    - winthier.signcolor.l
    - winthier.signcolor.m
    - winthier.signcolor.n
    - winthier.signcolor.o
    - winthier.signcolor.r
