name: Winthier
main: com.winthier.WinthierPlugin
version: 0.1
author: StarTux
description: The Winthier Plugin
depend: [ Vault, WorldEdit, WorldGuard ]
commands:
  winthier:
    description: General purpose command
    usage: /<command> help
    permission: winthier.winthier
permissions:
  winthier.wintier:
    description: Use the /winthier command
    default: op
  winthier.chat.pm:
    description: Send private messages via /msg, /tell, /reply or /r.
    default: op
  winthier.chat.me:
    description: Use the /me command.
    default: op
  winthier.password.notify:
    description: Get notified when a user gets promoted after entering the correct password.
    default: op
  winthier.playermessages.join:
    description: Display a message when the player joins the game.
    default: op
  winthier.playermessages.leave:
    description: Display a message when the player leaves the game.
    default: op
  winthier.playermessages.death:
    description: Display a message when the player dies.
    default: op
  winthier.deathmessage.visible:
    description: Send a message upon player death
    default: false
  winthier.noclientmods.exempt:
    description: Permit the use of cheaty clientmods.
    default: op
  winthier.signcolor.allcolors:
    description: Permit the use of all color codes on signs.
    default: op
    children:
    - winthier.signcolor.0
    - winthier.signcolor.1
    - winthier.signcolor.2
    - winthier.signcolor.3
    - winthier.signcolor.4
    - winthier.signcolor.5
    - winthier.signcolor.6
    - winthier.signcolor.7
    - winthier.signcolor.8
    - winthier.signcolor.9
    - winthier.signcolor.a
    - winthier.signcolor.b
    - winthier.signcolor.c
    - winthier.signcolor.d
    - winthier.signcolor.e
    - winthier.signcolor.f
  winthier.signcolor.allformats:
    description: Permit the use of all formatting codes on signs.
    default: op
    children:
    - winthier.signcolor.k
    - winthier.signcolor.l
    - winthier.signcolor.m
    - winthier.signcolor.n
    - winthier.signcolor.o
    - winthier.signcolor.r
  winthier.newbiewatch.notify:
    description: Get notified when a newbie breaks a watched block
    default: op
